### ISSUE TITLE
0.5.0 seems broken

### ISSUE THREAD

**Issue by dracan** [dracan/tomatoad#67]
I've just installed this from the installation file, and am just getting an empty overview window.

**Comment by dracan** [comment]
Exception is ..

```
Uncaught Error: Cannot find module 'vue'
    at Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (C:\Users\Dan\AppData\Local\Programs\Tomatoad\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at i (C:\Users\Dan\AppData\Local\Programs\Tomatoad\resources\app.asar\node_modules\vue-rate-it\dist\webpack:\webpack\universalModuleDefinition:6:1)
    at Object.<anonymous> (C:\Users\Dan\AppData\Local\Programs\Tomatoad\resources\app.asar\node_modules\vue-rate-it\dist\webpack:\webpack\bootstrap e0f97ef8fff70f861508:13:1)
    at Object.<anonymous> (C:\Users\Dan\AppData\Local\Programs\Tomatoad\resources\app.asar\node_modules\vue-rate-it\dist\vue-rate-it.min.js:3:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
```
